[package]
name = "policy-reasoner"
version = "0.1.0"
edition = "2021"
authors = [ "Bas Kloosterman", "Tim Müller" ]
repository.workspace = true
description = "Long-awaited implementation of the EPI Framework checkers, which reason about policies and contrain systems like [Brane](https://github.com/epi-project/brane)"


[workspace.package]
repository = "https://github.com/epi-project/policy-reasoner"


[dependencies]
tokio = { version = "1", features = ["full"] }
workflow = { path = "./lib/workflow" }
deliberation = { path = "./lib/deliberation" }
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
log = "0.4"
reasonerconn = { path = "./lib/reasonerconn" }
policy = { path = "./lib/policy" }
eflint-json = { path = "lib/eflint-json" }
srv = { path = "lib/srv" }
state-resolver = { path = "lib/state-resolver" }
async-trait = "*"
serde = {version="1.0", features=["derive"]}
serde_json = {version = "1.0" , features = ["raw_value"]}

[workspace]
resolver = "2"
members = [
    "lib/workflow",
    "lib/deliberation",
    "lib/reasonerconn",
    "lib/policy",
    "lib/eflint-json",
    "lib/srv",
    "lib/state-resolver",
]