[package]
name = "policy-builder"
version = "0.1.0"
edition = "2021"
authors = [ "Tim Müller" ]
description = "Tool for taking a collection of eFLINT files and compiling them to a single eFLINT JSON Spec."


[dependencies]
clap = { version = "4.4", features = ["derive"]}
console = "0.15"
error-trace = { git = "https://github.com/Lut99/error-trace-rs" }
futures-util = "0.3"
hex = "0.4"
hex-literal = "0.4"
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
indicatif = "0.17"
log = "0.4"
reqwest = { version = "0.11", features = ["stream"] }
sha2 = "0.10"
tokio = { version = "1.34", default-features = false, features = ["fs", "macros", "rt"]}
