[package]
name = "checker-client"
version = "0.1.0"
edition = "2021"
authors = [ "Bas Kloosterman", "Tim Müller" ]
repository = "https://github.com/epi-project/policy-reasoner"
description = "A tool to make requests to the checker conveniently, for demo/testing purposes."


[dependencies]
brane-ast = { git = "https://github.com/epi-project/brane" }
brane-shr = { git = "https://github.com/epi-project/brane" }
specifications = { git = "https://github.com/epi-project/brane" }
clap = { version = "4.4", features = ["derive"] }
console = "0.15"
enum-debug = { git = "https://github.com/Lut99/enum-debug", features = ["derive"] }
error-trace = { git = "https://github.com/Lut99/error-trace-rs" }
hmac = "0.12"
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
jwt = "0.16"
log = "0.4"
rand = "0.8"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = { version = "1.0", features = ["raw_value"] }
sha2 = "0.10"

deliberation = { path = "../../lib/deliberation" }
eflint-to-json = { path = "../../lib/eflint-to-json" }
srv = { path = "../../lib/srv" }
